
# To skip builds use [ci ckip] in GIT commit-msg
language: node_js

node_js:
  - "0.12"
  - "4.4"
  - "4.7"
  - "6.1"


env:
# default env is development
#  - NODE_ENV=
  - NODE_ENV=testing
#  - NODE_ENV=production

branches:
  only: []
  not: []

notifications:
  email:
    on_success: never

deploy:
  - provider: npm
    on:
      tags: true
    api_key:
      secure: Tk2YrZF2+gq1BNO8KR61JW4E4T0U/7/hr5ME+XP8iIgW2IMrljgwLNRfH1tzh/9+7D2Tcybxs5QcJgPwP+aSxvS1GpEwCXPw02TB7xgAtrD7CXB05aBovQc4v4mT6f84rfB50w0LWhG9DuIVX8K7NbDYB0qRhAx90STegii8ols=


