main: nodelib/0.0.1-dev

- type: application/x-project-mpe
  id: nodelib/0.0.1-dev

# Id: git-versioning/0.0.8-master package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.1-dev
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.8-master package.yaml



