type: application/x-project-mpe
id: nodelib/0.0.1-dev

# Id: git-versioning/0.0.6 package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.6
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.6 package.yaml


