# git-versioning main: nodelib

- type: application/vnd.org.wtwta.project
  main: nodelib
  id: nodelib

  name: nodelib
  version: 0.0.8 # nodelib
  environments: [ 'development' ]

  vendor: dotmpe
  distribution: public
  license: GPL-3.0

  pd-meta:
    check: "sh:tools/tags.sh:*.*:bin:src:test:tools grunt:check :git:status"
    test: "npm:test"
    build: "grunt:build"
    install: "npm:install"

    tasks:
      grep-filter: ./tools/sh/tags-filter.sh
      document: TODO.txt
      tags:
        - TODO # tasks:no-check
        - XXX # tasks:no-check
        - FIXME # tasks:no-check
        - BUG # tasks:no-check
        - NOTE # tasks:no-check


# Id: git-versioning/0.0.16-dev-master+20150504-0242 package.yaml
# Start

- type: application/vnd.org.wtwta.project
  id: git-versioning
  version: 0.0.16-dev-master+20150504-0242 # git-versioning
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.16-dev-master+20150504-0242 package.yaml
