main: nodelib

- type: application/x-project-mpe
  version: 0.0.5-dev+20150717-0005 # nodelib
  id: nodelib
  name: nodelib


# Id: git-versioning/0.0.16-dev+20150430-2153 package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.16-dev+20150430-2153 # git-versioning
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.16-dev+20150430-2153 package.yaml


