main: nodelib

- type: application/x-project-mpe
  version: 0.0.4-dev # nodelib
  id: nodelib


# Id: git-versioning/0.0.12 package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.12 # git-versioning
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.12 package.yaml


